spring:
  data:
    mongodb:
      database: movieDB
      host: localhost:27017
  redis:
    host: ${REDIS_PORT_6379_TCP_ADDR:localhost}
    port: ${REDIS_PORT_6379_TCP_PORT:6379}
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      key-prefix: mov
      time-to-live: 6000000
      use-key-prefix: true


