cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: eu-west-2
    s3:
      bucket-name: default-fairly-arriving-kite
    sqs:
      url: "https://sqs.eu-west-2.amazonaws.com/459265376359/default-fairly-arriving-kite-sqs"

spring:
  data:
    mongodb:
      database: movieDB
      host: ${MONGO_PORT_27017_TCP_ADDR}:${MONGO_PORT_27017_TCP_PORT}