spring:
  data:
    mongodb:
      database: movieDB
      host: ${MONGO_PORT_27017_TCP_ADDR:localhost}:${MONGO_PORT_27017_TCP_PORT:27017}
  redis:
    host: ${REDIS_PORT_6379_TCP_ADDR:localhost}
    port: ${REDIS_PORT_6379_TCP_PORT:6379}
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      key-prefix: mov
      time-to-live: {REDIS_TTL:600}
      use-key-prefix: true


