cloud:
  aws:
    credentials:
      access-key: ${AWS-ACCESS-KEY}
      secret-key: ${AWS-SECRET-KEY}
    region:
      static: eu-west-2
    s3:
      bucket-name: default-overly-talented-pelican

    sqs:
      url: "https://sqs.eu-west-2.amazonaws.com/459265376359/default-overly-talented-pelican-sqs"